
stages:          
  - build
  - test

  

build-job:       
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."

    - mvn clean package
  artifacts:
     paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn clean test  # Exécute les tests unitaires et d'intégration
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml  # Sauvegarde les résultats des testsgg
