
stages:          
  - build
  
build-job:       
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."

    - mvn clean package
  artifacts:
     paths:
      - target/*.jar


