stages:
  - build
  - test

image: openjdk:17

build-job:  # Nom du job inchangé
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - mvn test
  dependencies:
    - build-job  # Maintenant, cela correspond au nom du job de build