
stages:          
  - build
  - docker
variables:
  DOCKER_IMAGE: latifaes2/hello-world-java

  
build-job:       
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."

    - mvn clean package
  artifacts:
     paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   
    - docker build -t $DOCKER_IMAGE .
    
    - docker push $DOCKER_IMAGE


