
stages:          
  - build
  - docker
variables:
  DOCKER_IMAGE: latifaes2/hello-world-java
before_script:
  - apt-get update
  - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - docker --version
  - docker info
  
build-job:       
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."

    - mvn clean package
  artifacts:
     paths:
      - target/*.jar

docker-build:
  stage: docker
  script:
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   
    - docker build -t $DOCKER_IMAGE .
    
    - docker push $DOCKER_IMAGE


