
stages:          
  - build
  - docker
variables:
  DOCKER_IMAGE: latifaes2/hello-world-java
image: docker:20.10.7

before_script:
  - docker --version
  - docker info

build-job:       
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."

    - mvn clean package
  artifacts:
     paths:
      - target/*.jar

docker-build:
  stage: docker   
  image: docker:latest
  services:
    - docker:dind

  script:
    
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   
    - docker build -t $DOCKER_IMAGE .
    
    - docker push $DOCKER_IMAGE


