stages:
  - build
  - test
  - docker

image: openjdk:17

build-job:  # Nom du job inchangé
  stage: build
  image: maven:3.9.0-eclipse-temurin-17
  script:
    - echo "Compiling the code..."
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:3.8.4-openjdk-11
  script:
    - echo "tast l'app"

docker-build-push:
  stage: docker
  image: docker:latest  # Utilise l'image Docker officielle
  services:
    - docker:dind  # Active Docker-in-Docker (dind)
  variables:
    IMAGE_NAME: latifaes2/my-java-app  # Remplacez par votre nom de repository
    IMAGE_TAG: latest  
  script:
    - echo "Logging into Docker Hub..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - echo "Building Docker image..."
    
    - echo "Pushing Docker image to Docker Hub..."
    
  