apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 8
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: localhost:5000/hello-world
        ports:
        - containerPort: 8080
