apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conversation-api-pvc
  namespace: chatbot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
