apiVersion: v1
kind: ConfigMap
metadata:
  name: router-config
data:
  router.json: |
    {
      "ar": {
        "rasa_url": "http://rasa_arabic_chatbot-rasa-1:5006",
        "action_url": "http://rasa_arabic_chatbot-action_server-1:5056",
        "conversation_api": "http://rasa_arabic_chatbot-conversation_data_api-1:7002"
      },
      "fr": {
        "rasa_url": "http://rasa_french_chatbot-rasa-1:5005",
        "action_url": "http://rasa_french_chatbot-action_server-1:5055",
        "conversation_api": "http://rasa_french_chatbot-conversation_data_api-1:7000"
      }
    }
