apiVersion: v1
kind: Service
metadata:
  name: action-server-service
  namespace: chatbot
spec:
  selector:
    app: action-server
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055
      nodePort: 30059
  type: NodePort
