apiVersion: v1
kind: Service
metadata:
  name: conversation-data-api-service
  namespace: chatbot
spec:
  selector:
    app: conversation-data-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30088
  type: NodePort
