apiVersion: v1
kind: Service
metadata:
  name: rasa-fr-service
  namespace: chatbot
spec:
  selector:
    app: rasa-french
  ports:
    - port: 5005
      targetPort: 5005
  type: ClusterIP
