apiVersion: v1
kind: Service
metadata:
  name: chatbot-router-service
  namespace: chatbot
spec:
  selector:
    app: chatbot-router
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080  # Accessible via http://<node-ip>:30080
